[project]
name = "cloudflare-dyndns-updater"
version = "0.1.0"
description = "A script to automatically update Cloudflare DNS based on global IP address."
readme = "README.md"
authors = [
    { name = "netbub", email = "netbub1234@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "cloudflare>=5.6.0",
]

[project.scripts]
cloudflare-dyndns-updater = "cloudflare_dyndns_updater:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
